/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedbackmaintainer2;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CS
 */

public class tnamefeedteacher extends javax.swing.JInternalFrame {
public String s3;
    /**
     * Creates new form teacherfeedback
     */
   
    public tnamefeedteacher() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Of Feedbacks", "Course", "Excellent", "Good", "Average", "Poor", "%age"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 180, 620, 260);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Teacher ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 80, 30);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(110, 20, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Teacher Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 20, 110, 30);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(470, 20, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Phone No.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 60, 80, 30);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(110, 60, 140, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Gmail Account");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 70, 100, 30);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(470, 70, 140, 30);

        setBounds(0, 0, 678, 538);
    }// </editor-fold>//GEN-END:initComponents
void fetch()
{  
               String url="jdbc:mysql://localhost/feedback";
        try
        {
            Connection myconn=DriverManager.getConnection(url, "root", "");
            try
            {
              String q="select * from addteacher where teacherid=?";
                PreparedStatement state=myconn.prepareStatement(q);
                s3=loginteacher.teacherid;
                state.setString(1,s3 );
                
                
               DefaultTableModel mymodel1=(DefaultTableModel)jTable1.getModel();
               mymodel1.setRowCount(0);
               String q2="select * from tfeedback where tname=?";
                PreparedStatement state2=myconn.prepareStatement(q2);
           
                 
               ResultSet res=state.executeQuery();
               
                if(res.next())
                {
                   
                    jTextField2.setText(s3);
                    String s=res.getString("name");
                    jTextField3.setText(s);
                    jTextField4.setText(res.getString("phone"));
                    jTextField5.setText(res.getString("email"));
                    
                    state2.setString(1,s);   
                    ResultSet res2=state2.executeQuery();
                    
                    while(res2.next())
                    {
               String no=res2.getString("no");
               String course =res2.getString("cname");
               String e=res2.getString("excellent");
               String g=res2.getString("good");
               String a=res2.getString("average");
               String p=res2.getString("poor");
               String per=res2.getString("percentage");
               DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
               Object myrow[]={no,course,e,g,a,p,per};
               mymodel.addRow(myrow);
                    }
                } 
                if(jTable1.getRowCount()==0)
               {
                   JOptionPane.showMessageDialog(rootPane,"no subject alloted yet to you");
               }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Invalid Teacher");
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error in Queryhdfkla;k"+e.getMessage());
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection"+e.getMessage());
        }  
}
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
fetch();

    }//GEN-LAST:event_formInternalFrameActivated



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}