/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedbackmaintainer2;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CS
 */
public class tnamefeed extends javax.swing.JInternalFrame {

    /**
     * Creates new form teacherfeedback
     */
    public tnamefeed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose teacher" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(240, 70, 170, 40);

        jLabel2.setText("CHOOSE TEACHER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 30, 150, 30);

        jButton2.setText("FeedbackGenerator");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 130, 170, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Of Feedbacks", "Course", "Excellent", "Good", "Average", "Poor", "%age"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 620, 260);

        setBounds(0, 0, 678, 538);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

    }//GEN-LAST:event_jComboBox2ActionPerformed

void fetch()
{
         String url="jdbc:mysql://localhost/feedback";
try
{
    Connection myconn =DriverManager.getConnection(url, "root", "");
try
{  
    String q1="select * from addteacher";
    PreparedStatement state2=myconn.prepareStatement(q1);
    ResultSet res2=state2.executeQuery();
    while(res2.next())
    {
         jComboBox2.addItem(res2.getString("name"));
    }
/*vstate2
if(jComboBox2.getItemCount()==1)
{
    jComboBox2.removeAllItems();
    jComboBox2.addItem("no course available");
}*/
   
}
                 catch(SQLException e)
                    {
              JOptionPane.showMessageDialog(rootPane, "Error in Query"+e.getMessage());
                    } 
            finally
            {
                myconn.close();
            }
}
catch(Exception e)
{
   JOptionPane.showMessageDialog(rootPane, "Error in connection"+e.getMessage());  
}
}
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
fetch();        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  try
    {
        String url="jdbc:mysql://localhost/feedback";
        Connection myconn=DriverManager.getConnection(url, "root", "");
        try
        {
               DefaultTableModel mymodel1=(DefaultTableModel)jTable1.getModel();
               mymodel1.setRowCount(0);
            String q="select * from tfeedback where tname=?";
            
            PreparedStatement state=myconn.prepareStatement(q);
          
            
                String teacher=jComboBox2.getSelectedItem().toString();
                state.setString(1, teacher);
               
                
            ResultSet res=state.executeQuery();
           while(res.next())
           {
               String no=res.getString("no");
               String course =res.getString("cname");
               String e=res.getString("excellent");
               String g=res.getString("good");
               String a=res.getString("average");
               String p=res.getString("poor");
               String per=res.getString("percentage");
               
               DefaultTableModel mymodel=(DefaultTableModel)jTable1.getModel();
               Object myrow[]={no,course,e,g,a,p,per};
               mymodel.addRow(myrow);
           }
             if(jTable1.getRowCount()==0)
               {
                   JOptionPane.showMessageDialog(rootPane,"no teachers found for this subject");
               }
             
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "error in query"+e.getMessage());
        }
    }
    catch(SQLException e)
    {
       JOptionPane.showMessageDialog(rootPane, "error in connection"+e.getMessage());
    }            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}